export class User{
    #userID         // int
    #fullName       // String
    #studentNumber  // String
    #email          // String
    #password       // String
    #role           // UserRole, generated through studentNo
    #isActive = true// boolean

    constructor(fullName, studentNumber, email, password){
        // this.#userID; commented out as userID might be randomly/automatically generated
        this.#fullName = fullName;
        this.#studentNumber = studentNumber;
        this.#email = email;    
        this.#password = password;
        // this.#role = role; commented out as automatically generated by student number.
    }



}