export class User{
    #userID         // int
    #fullName       // String
    #studentNumber  // String
    #email          // String
    #passwordHash       // String
    #role           // UserRole, generated through studentNo
    #isActive = true// boolean

    constructor(fullName, studentNumber, email, password){
        // this.#userID; commented out as userID might be randomly/automatically generated
        this.#fullName = fullName;
        this.#studentNumber = studentNumber;
        this.#email = email;    
        this.#passwordHash = password;
        // this.#role = role; commented out as automatically generated by student number.
    }

    // GETTERS

    get getFullName() {return this.#fullName}
    get getStudentNo() {return this.#studentNumber}
    get getEmail() {return this.#email}
    get getRole() {return this.#role}

    // SETTERS

    
    

    // AUXILLARY METHODS


    deactivate(){
        if (this.#isActive){
            this.#isActive = false;
        }
    }

    authenticate(password){
        // Interface with Supabase to authenticate
    }

    updateProfile(){

    }

    hasPermission(action){

    }

}